OPTIM = fast_debug
BASE = ../rai
DEPEND = Core Kin Gui Geo KOMO Logic LGP Optim  PathAlgos
LIBS= -lboost_unit_test_framework -lboost_serialization -lboost_system -lpthread  -lboost_program_options
SRCS = $(PWD)/main.cpp $(PWD)/test1.cpp
OBJS = $(SRCS:%.cpp=%.o) 

include $(BASE)/makeutils/generic.mk
